### ISSUE TITLE
Changing the internal Hashfunction

### ISSUE THREAD

**Issue by Tockra** [10XGenomics/rust-boomphf#13]
Hi guys,

I wanted to know if there is a possibility to replace the wyhash part of the implementation with something else.

In all cases (u8 and u16 keys) the default hashmap with fnv or ahash seems to be faster then the mphf hashfunctions. 
That is not really cool.

T

**Comment by Tockra** [comment]
`test scan1_ser  ... bench:  55,010,930 ns/iter (+/- 3,001,733)`  seems to be very bad, when I compare with the original implementation:
```
bench lookups  sample size 10000000
BBhash bench lookups average 219.63 ns +- stddev  9.69 %   (fingerprint 4999580507664480)
```

**Comment by wangyi-fudan** [comment]
I am sad to see this. 
perhaps, wyhash emphesize quality first according to SMHasher, but second to speed. 
However, it should not  be so bad, something seems to be wrong.

**Comment by Tockra** [comment]
> 
> 
> I am sad to see this.
> perhaps, wyhash emphesize quality first according to SMHasher, but second to speed.
> However, it should not be so bad, something seems to be wrong.

I'm not realy sure, if a other hash function change anything. But I saw the function there and it could be a big part of the run time costs. So I just wanted to try a other hash function.

Maybe the runtime "55,010,930 ns/iter" means 55,010,930 ns for the whole measures (1000000u64). 
Then the implementation would be faster than the original. But I don't know. I think ns/iter means ns / iteration in the loop (build.rs).

**Comment by pmarks** [comment]
In the [benchmark scan11_ser](https://github.com/10XGenomics/rust-boomphf/blob/9bd02ab72f06414c48e04d15e845221f6a4a45cf/benches/build.rs#L30), the reported time is the ns per execution of the inner closure, which is computing the hash of 1M keys, so I believe that means we are getting 55 ns per computed hash. It's possible that there is speculative execution happening that is speeding up this benchmark artificially. I did some fairly careful benchmarking of `wyhash` vs `fnv` when I switched to wyhash & it was slightly better.

Can you describe your comparison with the standard HashMap in more detail? If you could add some benchmarks to the benchmark suite that would be a really useful! Then we could look at specific use cases & report some timings that would help people decide when to use this library. 

The standard hashmap has different tradeoffs: generally you only incur one main memory access to find your item, because the hash tells you exactly  where the key-value pair is in memory.  In the BoomHashMap, you incur a memory access for each bitvector you need to consult, plus another to get the final value. The main benefit of the BoomHashMap is that it gives you the option to not store the keys, which you must do in a normal hashmap.
