### ISSUE TITLE
panicked at 'attempt to shift left with overflow'

### ISSUE THREAD

**Issue by mokeyish** [10XGenomics/rust-boomphf#28]
'main' panicked at 'attempt to shift left with overflow'. 

https://github.com/10XGenomics/rust-boomphf/blob/b028cf9235b946754fb154a734ea97984ad12805/src/lib.rs#L58

**Comment by pmarks** [comment]
This can happen when the inputs have duplicates, or when the hash function isn't able to find distinct hashes for the input objects.  Can check for duplicates in your input data?  I will see if we can produce a better error message for this case.

**Comment by ozgrakkurt** [comment]
<del> this actually happens in wasm32 every time, without duplicates as well. In release mode, it loops forever. In debug mode crashes with `'main' panicked at 'attempt to shift left with overflow'.` as in top comment </del> actually found this issue is not related to mine. opened https://github.com/10XGenomics/rust-boomphf/issues/36
